name: 'Mogenius release Action'
description: 'Automate your release process with mogenius'

# Declare inputs
inputs:
  dev:
    description: 'Whether to use the dev API or not [ true | false ] (default: false)'
    required: false
    default: 'false'
  kind:
    description: 'Kubernetes Resource Type. Valid types are [Deployment | Daemonset | Statefulset | Replicaset | Job | Cronjob ] (default: Deployment)'
    required: true
    default: 'Deployment'
  namespace:
    description: 'The namespace your resource lives in'
    required: true
  resourceName:
    description: 'The name of the resource you want to change'
    required: true
  containerName:
    description: 'The name of the container you want to change'
    required: true
  image:
    description: 'The image you want to change to'
    required: true
  keyKind:
    description: 'The kind of the API key [ cluster | workspace ] (default: workspace)'
    required: true
    default: 'workspace'
  token:
    description: 'The API key for the mogenius API'
    required: true
  debug:
    description: 'Print input parameters for debugging'
    required: false
    default: false

runs:
  using: 'node20'
  main: 'dist/index.js'
